version: '3'

services:
  user:
    container_name: user-service
    build: ./backend/user
    ports:
      - "3001:3001"
    volumes:
      - ./backend/user:/app/src
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge