version: '3'

services:
  signup:
    container_name: signup-service
    build: ./backend/signup
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend/signup:/app/src
    networks:
      - backend-network
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile.dev
    container_name: postgres
    volumes:
      - "./database/data:/app/db"
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network
    ports:
      - "5432:5432"
networks:
  backend-network:
    driver: bridge